---
title: "Resolución de problemas"
format: html
 embed-resources: true
    toc: true
---


```{r}
# Librerías y carga de funciones
source("teoria_decision_funciones_incertidumbre.R")
library(ggplot2)

```
## 1. Primer problema: Resolución de tabla de decisión con los métodos vistos en clase.

 Usaremos una tabla de decisión con los mismos datos que la tarea realizado en Excel para la clase de teoría, así podremos comparar si los resultados son iguales.
 

```{r}
#| label: introducción de datos

pb1_datos <- crea.tablaX(c( 80, 60,	90,	70,	85,	75,
                95,	55,	65,	60,	70,	80,
                50,	45,	55,	60,	65,	70,
                90,	85, 95,	80,	75,	100,
                70,	60,	65,	55,	60,	65),
    numalternativas = 5, numestados = 6
)
```


### 1.1 Resolución en el caso favorable (beneficios)

```{r}
#| label: resolución en el caso favorable

criterio.Wald(pb1_datos, favorable = TRUE)#favorable = TRUE se refiere a beneficios
criterio.Optimista(pb1_datos, favorable = TRUE)
criterio.Hurwicz(pb1_datos, alfa = 0.4, favorable =TRUE)
criterio.Savage(pb1_datos, favorable = TRUE)#pesos son las pérdidas
criterio.Laplace(pb1_datos, favorable = TRUE) 
criterio.PuntoIdeal(pb1_datos, favorable = TRUE)

#Rectas del método Hurwicz
dibuja.criterio.Hurwicz(pb1_datos, favorable = TRUE)
dibuja.criterio.Hurwicz_Intervalos(pb1_datos, favorable = TRUE)

```

### 1.2 Resolución en el caso desfavorable (costos)

```{r}
#| label: resolución en el caso desfavorable

criterio.Wald(pb1_datos, favorable = FALSE)
criterio.Optimista(pb1_datos, favorable = FALSE)
criterio.Hurwicz(pb1_datos, alfa = 0.4, favorable =FALSE)
criterio.Savage(pb1_datos, favorable = FALSE)
criterio.Laplace(pb1_datos, favorable = FALSE) 
criterio.PuntoIdeal(pb1_datos, favorable = FALSE)

#Rectas del método Hurwicz
dibuja.criterio.Hurwicz(pb1_datos, favorable = FALSE)
dibuja.criterio.Hurwicz_Intervalos(pb1_datos, favorable = FALSE)
```

